FROM tognos_webdemo_os

ENV PYTHONPATH "/nv-caffe/python"

WORKDIR /nv-caffe

ADD . /nv-caffe

RUN pip install -r /nv-caffe/python/requirements.txt

RUN cd /nv-caffe && mkdir -p _docker_build && cd _docker_build && cmake -DCUDA_ARCH_NAME="All"  -DCUDA_ARCH_PTX="" .. && make -j9
