FROM tognos_webclient_os

ENV PYTHONPATH "/nv-caffe/python"

WORKDIR /nv-caffe

ADD . /nv-caffe

RUN pip install -r /nv-caffe/python/requirements.txt

RUN cd /nv-caffe && mkdir -p _build && cd _build && cmake -DCUDA_ARCH_NAME="Manual" -DCUDA_ARCH_BIN="30 35 50 52 60 61" -DCUDA_ARCH_PTX="" .. && make -j9
